export default function applicationTypes() {
  return {
    SET_WALLET_ADDRESS: 'SET_WALLET_ADDRESS',
    SET_WEB3: 'SET_WEB3',
    SET_DEFAULT_REFERRER: 'SET_DEFAULT_REFERRER',
    SET_USDT_BALANCE: 'SET_USDT_BALANCE',
    SET_TOKEN_BALANCE: 'SET_TOKEN_BALANCE',
    SET_DEPOSIT_DATA: 'SET_DEPOSIT_DATA',
    SET_IS_NEED_TO_UPDATE: 'SET_IS_NEED_TO_UPDATE',
    SET_IS_DEPOSIT_TRANSACTION: 'SET_IS_DEPOSIT_TRANSACTION',
    SET_IS_WITHDRAW_TRANSACTION: 'SET_IS_WITHDRAW_TRANSACTION',
    SET_NOT_CORRECT_CHAIN: 'SET_NOT_CORRECT_CHAIN',
    SET_REDIRECT_TO: 'SET_REDIRECT_TO',
    SET_TOAST_DATA: 'SET_TOAST_DATA',
    SET_BUY_TICKETS_AMOUNT: 'SET_BUY_TICKETS_AMOUNT',
    SET_LAST_WINNERS: 'SET_LAST_WINNERS',
    SET_CURRENT_TICKET_INDEX: 'SET_CURRENT_TICKET_INDEX',
    SET_CURRENT_TICKET_INDEX_LOADER: 'SET_CURRENT_TICKET_INDEX_LOADER'
  }
}
