export default function accountTypes() {
  return {
    SET_USER_WINNINGS: 'SET_USER_WINNINGS',
    SET_REFERRALS_BONUS: 'SET_REFERRALS_BONUS',
    SET_AVAILABLE_REWARD: 'SET_AVAILABLE_REWARD',
    SET_UPLINE: 'SET_UPLINE',
    SET_TOTAL_TICKETS_BOUGHT: 'SET_TOTAL_TICKETS_BOUGHT',
    RESET_USER_INFO: 'RESET_USER_INFO'
  }
}
